service: pickme # NOTE: update this with your service name

provider:
  name: aws
  region: us-west-2
  profile: sparkbox
  stage: dev
  runtime: nodejs10.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
